spring:
  thymeleaf:
    mode: HTML
    cache: false
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

logging:
  level:
    root: info
    com.kangmin: debug
  file:
    name: log/app-mongodb-blog-prod.log

application:
  env:
    node: PROD
