# common properties (shared by dev and prod)
# current default active profiles: dev
spring:
  thymeleaf:
    mode: HTML
    cache: false
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
