# common properties (shared by dev and prod)
# current default active profiles: dev
spring:
  config:
    use-legacy-processing: true
    import: file:env.properties
  thymeleaf:
    mode: HTML
    cache: false
  profiles:
    active: prod
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

# jwt
webapp:
  jwt:
    secretKeyStr: PleaseNoteThatTheLengthOfSecretKeyMustBeLongEnough
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 14
