# common properties (shared by dev and prod)
# current default active profiles: dev
spring:
  thymeleaf:
    mode: HTML
    cache: false
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test

logging:
  level:
    root: info
    com.kangmin: debug
  file:
    name: log/app-mongodb-blog-dev.log

server:
  port: 8080

application:
  env:
    node: DEV
